spring.application.name=disaster-resource-connector


spring.neo4j.uri=bolt+s://db-2f96a014.databases.cognodb.com
spring.neo4j.authentication.username=cognodb
spring.neo4j.authentication.password=60e289602ee3aa10e14bb72a54553897
